### ISSUE TITLE
J'ai un bug sur mes 2 raspberry après installation et reboot j'ai

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [Oliv4945/jarvis-systemd-startup#7]
Bonjour...

Depuis la mise à jour d'il y a quelque temps du core de Jarvis
mon crontab ne fonctionne plus....  @reboot ~/jarvis/jarvis.sh -b 
 j'ai donc voulu installer ce plugin...

Mais il me fait planter mais 2 raspbbery de la même manière....
jeudi 8 juin 2017, 11:24:50 (UTC+0200) [2mStarting RestAPI server on http://192.168.0.47:8083[0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [2mStarting RestAPI server on http://192.168.0.47:8083[0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [91mERROR: play command failed[0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [93mHELP: Verify your speaker in Settings > Audio > Speaker[0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) ERROR:  [Errno 98] Address already in use
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [95mjarvis[0m: J'ai rencontré une erreur, relancez-moi!
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [93mHELP: Verify your speaker in Settings > Audio > Speaker[0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [0m
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [95mjarvis[0m: J'ai rencontré une erreur, relancez-moi!
jeudi 8 juin 2017, 11:24:51 (UTC+0200) [93mHELP: Verify your speaker in Settings > Audio > Speaker[0m
jeudi 8 ju

Il me faut faire obligatoirement un "Step-by-step wizard" pour le redémmarer un peu.... sans rien faire il plante de la même manière...

**Comment by Oliv4945** [comment]
Surprenant. Que donne `sudo journalctl -f -u jarvis.service` ?

**Comment by Oliv4945** [comment]
@Jean-Bernard-Hallez . As-tu des nouvelles ?

**Comment by Jean-Bernard-Hallez** [comment]
Oui j'ai contourné la solution en rajoutant dans le crontab:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
puis ma commande 
@reboot ~/jarvis/jarvis.sh -b
solution donné par Alex... Je clôture.
